name: Build mrHARDI docker

on:
  push:
    branches:
      - 'develop'

jobs:
  buildx_bake:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build image stack
        uses: docker/bake-action@v2.1.0
        working-directory: ./containers
        with:
          pull: true
          push: false
