version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    labels:
      - "Github Actions Update"
    schedule:
      interval: "daily"
