---
# Default values for provisioning

tmp_dir: "/tmp"
n_procs: 1

pysrc_ver_major: 3
pysrc_ver_minor: 7
pysrc_ver_rev: 5
pysrc_ver: "{{ pysrc_ver_major }}.{{ pysrc_ver_minor }}.{{ pysrc_ver_rev }}"
pysrc_ver_s: "{{ pysrc_ver_major }}.{{ pysrc_ver_minor }}"
pysrc_pkg_name: "Python-{{ pysrc_ver }}"
pysrc_url: "https://www.python.org/ftp/python/{{ pysrc_ver }}/{{ pysrc_pkg_name }}.tgz"
pysrc_dir: "{{ tmp_dir }}/{{ pysrc_pkg_name }}"
pysrc_pkg: "{{ pysrc_dir }}.tgz"
pydest_dir: "/shared_python"

mrh_setup_install: "develop"

pysrc_cleanup: no
pydest_overwrite: no