---

- name: Check for presence of custom Python
  command: python{{ pysrc_ver_major }} --version
  register: py_installed
  failed_when: py_installed.stdout == pydest_ver and not pydest_overwrite
  ignore_errors: yes

- name: Download Python tar
  get_url: url="{{ pysrc_url }}" dest="{{ pysrc_pkg }}"

- name: Untar Python package
  unarchive:
    src: "{{ pysrc_pkg }}"
    dest: "{{ tmp_dir }}"
    copy: no
    creates: "{{ pysrc_dir }}"
  become: yes

- name: Configure Python
  command:
    argv:
      - "./configure"
      - "--enable-optimizations"
      - "--prefix={{ pydest_dir }}"
      - "--exec-prefix={{ pydest_dir }}"
      - "--with-ensurepip=install"
      - "--enable-shared"
      - "--with-system-ffi"
    chdir: "{{ pysrc_dir }}"
    creates: "{{ pysrc_dir }}/Makefile"
  become: yes

- name: Make Python
  command: make -j "{{ n_procs }}"
  args:
    chdir: "{{ pysrc_dir }}"
    creates: "{{ pysrc_dir }}/build/scripts-{{ pysrc_ver_s }}/pyvenv-{{ pysrc_ver_s }}"

- name: Make Python install
  command: make install -j "{{ n_procs }}"
  args:
    chdir: "{{ pysrc_dir }}"
    creates: "{{ pydest_dir }}/bin/python{{ pysrc_ver_s }}m"
  register: py_bin_installed
  become: yes

- name: Give rights to Python to vagrant vm user
  file:
    path: "{{ pydest_dir }}"
    state: directory
    recurse: yes
    owner: vagrant
  become: yes
  when: py_bin_installed is not skipped

- name: Add Python alternative
  command:
    argv:
      - "update-alternatives"
      - "--install"
      - "/usr/local/bin/python{{ pysrc_ver_major }}"
      - "python{{ pysrc_ver_major }}"
      - "{{ pydest_dir }}/bin/python{{ pysrc_ver_s }}m"
      - "1"
  become: yes
  when: py_bin_installed is not skipped

- name: Add Pip alternative
  command:
    argv:
      - "update-alternatives"
      - "--install"
      - "/usr/local/bin/pip{{ pysrc_ver_major }}"
      - "pip{{ pysrc_ver_major }}"
      - "{{ pydest_dir }}/bin/pip{{ pysrc_ver_s }}"
      - "1"
  become: yes
  when: py_bin_installed is not skipped

- name: Set Python as main alternative
  command:
    argv:
      - "update-alternatives"
      - "--set"
      - "python{{ pysrc_ver_major }}"
      - "{{ pydest_dir }}/bin/python{{ pysrc_ver_s }}m"
      - "--force"
  when: py_bin_installed is not skipped

- name: Create Python non minimal symbolic link
  file:
    src: "{{ pydest_dir }}/bin/python{{ pysrc_ver_s }}m"
    dest: "{{ pydest_dir }}/bin/python{{ pysrc_ver_s }}"
    state: link
  when: py_bin_installed is not skipped

- name: Set Pip as main alternative
  command:
    argv:
      - "update-alternatives"
      - "--set"
      - "pip{{ pysrc_ver_major }}"
      - "{{ pydest_dir }}/bin/pip{{ pysrc_ver_major }}"
      - "--force"
  when: py_bin_installed is not skipped

- name: Clean up sources
  command: rm "{{ item }}"
  with_items:
    - "-r {{ pysrc_pkg }}"
    - "-rf {{ pysrc_dir }}"
  when: pysrc_cleanup
