---

- name: Install mrHARDI requirements
  command: pip{{ pysrc_ver_major }} install -r requirements.txt
  args:
    chdir: "{{ mrh_dir }}"

- name: Install mrHARDI inside Python
  command: python{{ pysrc_ver_major }} setup.py {{ mrh_setup_install }}
  args:
    chdir: "{{ mrh_dir }}"
