---

- name: Run preinstallation block
  include: apt_get.yml

- name: Run python installation block
  include: build_python.yml
  ignore_errors: yes

- name: Run MMY installation block
  include: install_mmy.yml

- name: Run Nextflow installation block
  include: install_nxf.yml
