name: Build mrHARDI docker

on:
  push:
    branches:
      - 'master'

jobs:
  buildx_bake:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build image stack and push
        uses: docker/bake-action@78e325fad8b5b74acf4be76f371e8e7577e527d7
        with:
          working-directory: ./containers
          pull: true
          push: true
