name: Build mrHARDI docker

on: push

jobs:
  buildx_bake:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - 
        name: Get release number
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build image stack and push
        uses: docker/bake-action@78e325fad8b5b74acf4be76f371e8e7577e527d7
        with:
          working-directory: ./containers
          pull: true
          push: true
      - 
        name: Build singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
        run: |
          mkdir -p mrhardi/singularity
          sudo singularity build mrhardi/singularity/mrhardi_gpu_${{ github.event.release.tag_name }}.sif docker://avcaron/mrhardi:gpu
      - 
        name: Upload singularity images to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            mrhardi/singularity/mrhardi_gpu_${{ github.event.release.tag_name }}.sif
