name: Build mrHARDI docker

on:
  push:
    branches:
      - 'develop'
      - 'feat/github_ci'

jobs:
  mrhardi-creative-bakery:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      -
        name: Maximize disk usage
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          temp-reserve-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build docker image stack
        uses: docker/bake-action@78e325fad8b5b74acf4be76f371e8e7577e527d7
        with:
          working-directory: ./containers
          pull: true
          push: true
          set: |
            nogpu.tags=docker.io/avcaron/mrhardi-dev:nogpu
            latest.tags=docker.io/avcaron/mrhardi-dev:gpu
      - 
        name: Setup singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.7.1
      -
        name: Build singularity
        run: |
          mkdir -p mrhardi/singularity
          singularity build mrhardi/singularity/gpu.sif docker://avcaron/mrhardi-dev:gpu
      -
        name : Upload workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mrhardi_develop
          path: mrhardi/
          retention-days: 14
          if-no-files-found: warn
