name: Development PR builds

on:
  pull_request:
    branches:
      - develop
    types: [opened,reopened,synchronize]
    paths:
      - 'magic_monkey/**/*.py'
      - 'setup.py'
      - '!.github/**'
      - '.github/workflows/*-develop.yml'
      - 'containers/**/*'

jobs:
  mrhardi-creative-bakery:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Get git diff for the current modifications
        uses: technote-space/get-diff-action@v6.1.0
        id: git_diff
        with:
          GET_FILE_DIFF: true
          PATTERNS: |
            magic_monkey/**/*.py
            setup.py
            .github/workflows/*-develop.yml
            containers/**/*
      -
        name: Set up Docker Buildx
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build docker image stack
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: docker/bake-action@78e325fad8b5b74acf4be76f371e8e7577e527d7
        with:
          working-directory: ./containers
          pull: true
          push: true
          set: |
            nogpu.tags=docker.io/avcaron/mrhardi-nogpu:pr-${{ github.event.number }}
            latest.tags=docker.io/avcaron/mrhardi-gpu:pr-${{ github.event.number }}
            mrhardi_cloner.args.mrhardi_ver=${{ github.head_ref }}
      -
        name: Write artifacts manifest
        run: |
          echo "Warning !!! Artifacts will be deleted when pull request closes" >> artifacts.MANIFEST
          echo "Artifacts pull commands:" >> artifacts.MANIFEST
          echo "docker pull avcaron/mrhardi-nogpu:pr-${{ github.event.number }}" >> artifacts.MANIFEST
          echo "docker pull avcaron/mrhardi-gpu:pr-${{ github.event.number }}" >> artifacts.MANIFEST
      -
        name: Upload workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts_manifest
          path: artifacts.MANIFEST
          if-no-files-found: warn
