name: Build mrHARDI docker

on:
  push:
    branches:
      - 'feat/github_ci'
    tags:
      - 'v*'

jobs:
  mrhardi-bakery:
      runs-on: ubuntu-latest
      environment: CI

      steps:
        -
          name: Checkout
          uses: actions/checkout@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - 
          name: Configure docker tags for the current release
          id: docker_tags
          uses: docker/metadata-action@v4
          with:
            images: |
              mrhardi/mrhardi
              mrhardi/mrhardi-gpu
              mrhardi/mrhardi-nogpu
            tags: |
              type=semver,pattern={{raw}}
              type=ref,event=branch
        -
          name: Rebuild complete docker image stack with dependencies
          uses: docker/bake-action@78e325fad8b5b74acf4be76f371e8e7577e527d7
          with:
            working-directory: ./containers
            files: |
              ./docker-bake.hcl
              ${{ steps.docker_tags.outputs.bake-file }}
            targets: full
            pull: true
            push: true

  mrhardi-packaging:
    needs: mrhardi-bakery
    runs-on: ubuntu-latest
    environment: CI

    steps:
      -
        name: Maximize disk usage
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          temp-reserve-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - 
        name: Setup singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.7.1
      - 
        name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          login-server: mrhardi.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}
      -
        name: Build and push singularity
        run: |
          mkdir -p mrhardi/singularity
          mkdir sif_tmp sif_cache
          export SINGULARITY_TMPDIR="$(pwd)/sif_tmp"
          export SINGULARITY_CACHEDIR="$(pwd)/sif_cache"
          echo "Caching and temping singularity at : $SINGULARITY_CACHEDIR and $SINGULARITY_TMPDIR"
          singularity build mrhardi.sif docker://avcaron/mrhardi:latest
          echo "${{ secrets.ACR_TOKEN }}" | singularity remote login --username ${{ secrets.ACR_USERNAME }} --password-stdin oras://mrhardi.azurecr.io
          singularity push mrhardi.sif mrhardi.azurecr.io/mrHARDI/mrhardi:latest
          singularity push mrhardi.sif mrhardi.azurecr.io/mrHARDI/mrhardi:${{ github.event.release.tag_name }}
