name: Development PR builds

on:
  pull_request:
    branches:
      - develop
    types: [opened,reopened,synchronize]
    paths:
      - 'mrHARDI/**/*.py'
      - 'setup.py'
      - 'requirements.txt'
      - '!.github/**'
      - '.github/workflows/*-develop.yml'
      - 'containers/**/*'

jobs:
  mrhardi-creative-bakery:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Get git diff for the current modifications
        uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          GET_FILE_DIFF: true
          PATTERNS: |
            mrHARDI/**/*.py
            setup.py
            .github/workflows/*-develop.yml
            containers/**/*
      -
        name: Maximize disk usage
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          temp-reserve-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      -
        name: Checkout
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build docker image stack
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: docker/bake-action@v2.3.0
        with:
          workdir: ./containers
          pull: true
          push: true
          set: |
            mrhardi.tags=docker.io/avcaron/mrhardi:pr-${{ github.event.number }}
            mrhardi_cloner.args.mrhardi_ver=${{ github.head_ref }}
      -
        name: Write artifacts manifest
        run: |
          echo "Warning !!! Artifacts will be deleted when pull request closes" >> artifacts.MANIFEST
          echo "Artifacts pull commands:" >> artifacts.MANIFEST
          echo "docker pull avcaron/mrhardi:pr-${{ github.event.number }}" >> artifacts.MANIFEST
      -
        name: Upload workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts_manifest
          path: artifacts.MANIFEST
          if-no-files-found: warn
