name: Build mrHARDI docker

on:
  push:
    branches:
      - 'develop'
      - 'feat/github_ci'

jobs:
  buildx_bake:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Enable docker cache resolution
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build docker image stack
        uses: docker/bake-action@78e325fad8b5b74acf4be76f371e8e7577e527d7
        with:
          working-directory: ./containers
          pull: true
          load: true
          set: |
            nogpu.output=type=docker
            latest.output=type=docker
      -
        name : Save docker artifacts
        run: |
          mkdir -p mrhardi/docker
          docker image list
          docker save -o mrhardi/docker/nogpu.tar avcaron/mrhardi:nogpu
          docker save -o mrhardi/docker/gpu.tar avcaron/mrhardi:gpu
      - 
        name: Setup singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
      -
        name: Build singularity images
        run: |
          mkdir -p mrhardi/singularity
          sudo singularity build mrhardi/singularity/nogpu.sif docker-archive://mrhardi/docker/nogpu.tar
          sudo singularity build mrhardi/singularity/gpu.sif docker-archive://mrhardi/docker/gpu.tar
      -
        name : Upload workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mrhardi_develop
          path: mrhardi/
          retention-days: 14
          if-no-files-found: warn
