name: Build mrHARDI docker

on:
  push:
    branches:
      - 'develop'
      - 'feat/github_ci'

jobs:
  mrhardi-creative-bakery:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Get git diff for the current modifications
        uses: technote-space/get-diff-action@v4.0.1
        id: git-diff
        with:
          PATTERNS: |
            containers/
            magic_monkey/**/*.py
            setup.py
      -
        name: Set up Docker Buildx
        if: steps.git-diff.count > 0
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        if: steps.git-diff.count > 0
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build docker image stack
        if: steps.git-diff.count > 0
        uses: docker/bake-action@78e325fad8b5b74acf4be76f371e8e7577e527d7
        with:
          working-directory: ./containers
          pull: true
          push: true
          set: |
            nogpu.tags=docker.io/avcaron/mrhardi-nogpu:dev
            latest.tags=docker.io/avcaron/mrhardi-gpu:dev

  mrhardi-creative-packaging:
    needs: mrhardi-creative-bakery
    runs-on: ubuntu-latest
    environment: CI

    steps:
      -
        name: Maximize disk usage
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          temp-reserve-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - 
        name: Setup singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.7.1
      - 
        name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          login-server: mrhardi.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}
      -
        name: Build and push singularity
        run: |
          mkdir -p mrhardi/singularity
          mkdir sif_tmp sif_cache
          export SINGULARITY_TMPDIR="$(pwd)/sif_tmp"
          export SINGULARITY_CACHEDIR="$(pwd)/sif_cache"
          echo "Caching and temping singularity at : $SINGULARITY_CACHEDIR and $SINGULARITY_TMPDIR"
          singularity build mrhardi_dev_gpu.sif docker://avcaron/mrhardi-gpu:dev
          echo "${{ secrets.ACR_TOKEN }}" | singularity remote login --username ${{ secrets.ACR_USERNAME }} --password-stdin oras://mrhardi.azurecr.io
          singularity push mrhardi_dev_gpu.sif oras://mrhardi.azurecr.io/mrHARDI/mrhardi:dev
      -
        name: Write artifacts manifest
        run: |
          echo "Artifacts pull commands:" >> artifacts.MANIFEST
          echo "docker pull avcaron/mrhardi-nogpu:dev" >> artifacts.MANIFEST
          echo "docker pull avcaron/mrhardi-gpu:dev" >> artifacts.MANIFEST
          echo "singularity pull oras://mrhardi.azurecr.io/mrHARDI/mrhardi:dev" >> artifacts.MANIFEST
      -
        name: Upload workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts_manifest
          path: artifacts.MANIFEST
          if-no-files-found: warn
