name: Update development artifacts

on:
  pull_request:
    branches:
      - develop
    types: [closed]
    paths:
      - 'mrHARDI/**/*.py'
      - 'setup.py'
      - '!.github/**'
      - '.github/workflows/*-develop.yml'
      - 'containers/**/*'

permissions:
  id-token: write
  contents: read

jobs:
  create_singularity_dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: CI

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Get git diff for the current modifications
        uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          GET_FILE_DIFF: true
          PATTERNS: |
            mrHARDI/**/*.py
            setup.py
            .github/workflows/*-develop.yml
            containers/**/*
      -
        name: Maximize disk usage
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          temp-reserve-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - 
        name: Setup singularity
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.7.1
      - 
        name: Azure Container Registry Login
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: Azure/docker-login@v1
        with:
          login-server: mrhardi.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}
      -
        name: Build and push singularity
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        run: |
          mkdir -p mrhardi/singularity
          mkdir sif_tmp sif_cache
          export SINGULARITY_TMPDIR="$(pwd)/sif_tmp"
          export SINGULARITY_CACHEDIR="$(pwd)/sif_cache"
          echo "Caching and temping singularity at : $SINGULARITY_CACHEDIR and $SINGULARITY_TMPDIR"
          singularity build mrhardi_dev.sif docker://avcaron/mrhardi:pr-${{ github.event.number }}
          echo "${{ secrets.ACR_TOKEN }}" | singularity remote login --username ${{ secrets.ACR_USERNAME }} --password-stdin oras://mrhardi.azurecr.io
          singularity push mrhardi_dev.sif oras://mrhardi.azurecr.io/mrHARDI/mrhardi:dev

  create_docker_dev:
    needs: create_singularity_dev
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - 
        name: Create docker dev tag from PR tag
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: julb/action-copy-docker-tag@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          from: avcaron/mrhardi:pr-${{ github.event.number }}
          tags: |
            avcaron/mrhardi:dev
      -
        name: Delete PR tag from dockerhub
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: mhl787156/dockerhub-delete-tag-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
          organisation: avcaron
          image: mrhardi
          tag: pr-${{ github.event.number }}