name: Create master release

on:
  pull_request:
    branches:
      - master
    types: [closed]
    paths:
      - 'mrHARDI/**/*.py'
      - 'setup.py'
      - 'requirements.txt'
      - 'containers/**/*'

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: CI

    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    steps:
      -
        name: Increment minor tag
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          use_github_release_notes: true
