name: Update development artifacts

on:
  pull_request:
    branches:
      - develop
    types: [closed]
    paths:
      - 'magic_monkey/**/*.py'
      - 'setup.py'
      - '!.github/**'
      - '.github/workflows/*-develop.yml'
      - 'containers/**/*'

jobs:
  create_docker_dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: CI

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Get git diff for the current modifications
        uses: technote-space/get-diff-action@v6.1.0
        id: git_diff
        with:
          GET_FILE_DIFF: true
          PATTERNS: |
            magic_monkey/**/*.py
            setup.py
            .github/workflows/*-develop.yml
            containers/**/*
      - 
        name: Create CPU docker dev tag from PR tag
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: julb/action-copy-docker-tag@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          from: avcaron/mrhardi-nogpu:pr-${{ github.event.number }}
          tags: |
            avcaron/mrhardi-nogpu:dev
      -
        name: Delete CPU PR tag from dockerhub
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: mhl787156/dockerhub-delete-tag-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
          organisation: avcaron
          image: mrhardi-nogpu
          tag: pr-${{ github.event.number }}
      - 
        name: Create GPU docker dev tag from PR tag
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: julb/action-copy-docker-tag@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          from: avcaron/mrhardi-gpu:pr-${{ github.event.number }}
          tags: |
            avcaron/mrhardi-gpu:dev
      -
        name: Delete GPU PR tag from dockerhub
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: mhl787156/dockerhub-delete-tag-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
          organisation: avcaron
          image: mrhardi-gpu
          tag: pr-${{ github.event.number }}

  create_singularity_dev:
    needs: create_docker_dev
    runs-on: ubuntu-latest
    environment: CI

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Get git diff for the current modifications
        uses: technote-space/get-diff-action@v6.1.0
        id: git_diff
        with:
          GET_FILE_DIFF: true
          PATTERNS: |
            magic_monkey/**/*.py
            setup.py
            .github/workflows/*-develop.yml
            containers/**/*
      - 
        name: Setup singularity
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.7.1
      -
        name: Update tag of singularity image
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        run: |
          mkdir sif_tmp sif_cache
          export SINGULARITY_TMPDIR="$(pwd)/sif_tmp"
          export SINGULARITY_CACHEDIR="$(pwd)/sif_cache"
          echo "Caching and temping singularity at : $SINGULARITY_CACHEDIR and $SINGULARITY_TMPDIR"
          singularity pull oras://mrhardi.azurecr.io/mrHARDI/mrhardi:pr-${{ github.event.number }}
          echo "${{ secrets.ACR_TOKEN }}" | singularity remote login --username ${{ secrets.ACR_USERNAME }} --password-stdin oras://mrhardi.azurecr.io
          singularity push mrhardi_pr-${{ github.event.number }}.sif oras://mrhardi.azurecr.io/mrHARDI/mrhardi:dev
      -
        name: Azure Container Registry Login
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      -
        name: Delete PR tag from ACR
        if: ${{ steps.git_diff.outputs.lines > 0 }}
        run: |
          az acr repository untag -n mrHARDI -t mrhardi:pr-${{ github.event.number }}
